version: '3.1'

volumes:
  dados:

# Defenição de redes (criacao segregada)
networks:
  banco:
  web:
  fila:

services:
  db:
    image: postgres:13.0
    container_name: 'database-pj-final'
    restart: always
    networks:
      - banco
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data

      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: python:latest
    container_name: 'backend-pj-final'
    environment:
      - DB_HOST=db
      - DB_NAME=email_sender
      - DB_USER=postgres
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    # Definindo conexoes de redes
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue

  frontend:
    image: nginx:latest
    container_name: 'frontend-pj-final'
    networks:
      - web
    depends_on:
      - app
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

  queue:
    image: redis:latest
    container_name: 'queue-pj-final'
    networks:
      - fila

  worker:
    build: worker
    working_dir: /worker
    volumes:
      - ./worker:/worker
    command: worker.py
    networks:
      - fila
    depends_on:
      - queue
      - app